name: ${PROJECT}-test
services:
  db:
    volumes:
      - project-db-test:/var/lib/postgresql/data
  minio:
    volumes:
      - project-minio-db-test:/data

volumes:
  project-db-test:
    name: ${PROJECT}-db-test
  project-minio-db-test:
    name: ${PROJECT}-minio-db-test
